apiVersion: v1
kind: Service
metadata:
  name: zqflow
  namespace: default
  labels:
    app.kubernetes.io/name: zqflow
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: zqflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80