apiVersion: v1
kind: Service
metadata:
  name: zqwf01
  namespace: zqwf01-ns
  labels:
    app.kubernetes.io/name: zqwf01
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: zqwf01
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000